---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks: 
      - name: Import VPC setup variable
        include_vars: vars/bastion_setup
        
      - name: Import VPC setup Variable
        include_vars: vars/output_vars
        
      - name: Create vprofile ec2 key
        ec2_key:
           name: vprofile-key
           region: "{{region}}"
        register: key_out
        
      - name: Save private key into file bastion-key.pem
        copy:
          content: "{{key_out.key.private_key}}"
          dest: "./bastion-key.pem"
          mode: 0600
        when: key_out.changed
      
